{
    "name": "T&I Product Intelligence System",
    "summary": "Product governance, UID generation, duplicate prevention, and price intelligence for Odoo 16.",
    "version": "16.0.1.0.0",
    "category": "Manufacturing/Product Governance",
    "author": "T&I Projects Limited",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "product",
        "purchase",
        "sale_management",
        "stock",
        "mrp",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ti_product_data.xml",
        "data/ir_cron_data.xml",
        "views/ti_product_category_views.xml",
        "views/ti_product_uid_rule_views.xml",
        "views/product_template_views.xml",
        "views/ti_product_duplicate_views.xml",
        "views/product_price_history_views.xml",
        "views/ti_product_dashboard_views.xml",
        "wizard/ti_product_creation_wizard_views.xml",
        "wizard/ti_product_merge_wizard_views.xml",
        "wizard/ti_product_migration_wizard_views.xml",
        "views/purchase_sale_views.xml",
        "views/ti_product_menus.xml",
    ],
    "demo": [
        "demo/ti_product_demo.xml",
    ],
    "application": True,
    "installable": True,
}

